extToLang() {
    case $1 in
        py) echo "Python" ;;
        ts) echo "TypeScript" ;;
        tsx) echo "TypeScript" ;;
        css) echo "CSS" ;;
        glsl) echo "GLSL" ;;
        cpp) echo "C++" ;;
        *)  echo "Unknown language for extension: $1" >&2;
            exit 1 ;;
    esac
}

genListings() {
    name=$1
    repoLoc=$2
    langExts=(py ts tsx css glsl cpp)
    echo "\subsection{$name}"
    echo "See~\cite{${name}} for the corresponding git repository."
    for ext in "${langExts[@]}"; do
        lang=$(extToLang "$ext")
        for f in $(find "$repoLoc" -type f -name "*.$ext"); do
            echo "\\lstinputlisting[language=$lang,caption={\detokenize{${f#"$repoLoc/"}}}]{\detokenize{$f}}"
        done
    done
}

genAllListings() {
    echo "% Autogenerated by gen-listings.bash - Don't edit by hand"
    genListings dt-lif-snn-compute-regions-depthsearch code/dt-lif-snn-compute-regions-depthsearch 

    genListings dt-lif-snn-compute-regions code/dt-lif-snn-compute-regions 

    genListings dt-lif-snn-visualizer code/dt-lif-snn-visualizer 
}

genAllListings > src/listings.tex
